import type { TimePickerState, StudioPreset } from "../types";

export const DEFAULT_TIMEPICKER_STATE: TimePickerState = {
  "showHelper": true,
  "showSuccess": false,
  "width": 430,
  "height": 130,
  "gap": 10,
  "padding": 18,
  "radius": 18,
  "borderWidth": 1,
  "borderStyle": "solid",
  "fontBucket": "google",
  "fontSearch": "",
  "systemFontIdx": 9,
  "googleFontFamily": "Inter",
  "fontSizeUnit": "px",
  "titleSize": 22,
  "bodySize": 14,
  "fontStyle": "normal",
  "textTransform": "none",
  "textDecoration": "none",
  "letterSpacing": 0,
  "letterSpacingUnit": "px",
  "lineHeight": 1.5,
  "radiusLinked": true,
  "radiusTL": 22,
  "radiusTR": 22,
  "radiusBR": 22,
  "radiusBL": 22,
  "shadowEnabled": true,
  "shadowX": 0,
  "shadowY": 8,
  "shadowBlur": 24,
  "shadowSpread": 0,
  "shadowOpacity": 0.25,
  "shadowColor": "#000000",
  "focusRingEnabled": true,
  "focusRingWidth": 2,
  "focusRingOffset": 2,
  "focusRingColor": "#38bdf8",
  "transitionDuration": 200,
  "transitionEasing": "ease",
  "background": "#0f172a",
  "foreground": "#e5eefb",
  "muted": "#94a3b8",
  "accent": "#38bdf8",
  "border": "#334155",
  "labelSize": 15,
  "inputSize": 16,
  "fontWeight": 650,
  "focusRing": 3,
  "previewState": "default",
  "label": "Meeting time",
  "description": "Native time field with min, max, step, and accessible helper copy.",
  "helper": "Use 15 minute increments.",
  "errorText": "Choose a time inside office hours.",
  "successText": "Time is available.",
  "value": "09:30",
  "min": "08:00",
  "max": "18:00",
  "step": 900,
  "id": "meeting-time",
  "name": "meetingTime",
  "title": "Meeting time",
  "tabIndex": 0,
  "dir": "ltr",
  "lang": "en",
  "autocomplete": "off",
  "inputMode": "numeric",
  "enterKeyHint": "done",
  "showSeconds": false,
  "showTimezone": true,
  "timezoneLabel": "Local time",
  "showClearAction": true,
  "required": true,
  "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
  "errorColor": "#ef4444",
  "successColor": "#22c55e",
  "readOnly": false,
  "invalid": false
};

export const TIMEPICKER_PRESETS: StudioPreset[] = [
  {
    "id": "premium-glass-compact",
    "family": "premium",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "premium",
      "glass",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 24,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "premium-glass-spacious",
    "family": "premium",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "premium",
      "glass",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 24,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "premium-soft-compact",
    "family": "premium",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "premium",
      "soft",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 28,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "premium-soft-spacious",
    "family": "premium",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "premium",
      "soft",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 28,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "premium-crisp-compact",
    "family": "premium",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "premium",
      "crisp",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 12,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "premium-crisp-spacious",
    "family": "premium",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "premium",
      "crisp",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 12,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "premium-hero-compact",
    "family": "premium",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "premium",
      "hero",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 30,
      "borderWidth": 2,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "premium-hero-spacious",
    "family": "premium",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "premium",
      "hero",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 30,
      "borderWidth": 2,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "editorial-glass-compact",
    "family": "editorial",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "editorial",
      "glass",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 24,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "editorial-glass-spacious",
    "family": "editorial",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "editorial",
      "glass",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 24,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "editorial-soft-compact",
    "family": "editorial",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "editorial",
      "soft",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 28,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "editorial-soft-spacious",
    "family": "editorial",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "editorial",
      "soft",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 28,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "editorial-crisp-compact",
    "family": "editorial",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "editorial",
      "crisp",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 12,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "editorial-crisp-spacious",
    "family": "editorial",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "editorial",
      "crisp",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 12,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "editorial-hero-compact",
    "family": "editorial",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "editorial",
      "hero",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 30,
      "borderWidth": 2,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "editorial-hero-spacious",
    "family": "editorial",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "editorial",
      "hero",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 30,
      "borderWidth": 2,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "admin-glass-compact",
    "family": "admin",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "admin",
      "glass",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 24,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "admin-glass-spacious",
    "family": "admin",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "admin",
      "glass",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 24,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "admin-soft-compact",
    "family": "admin",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "admin",
      "soft",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 28,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "admin-soft-spacious",
    "family": "admin",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "admin",
      "soft",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 28,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "admin-crisp-compact",
    "family": "admin",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "admin",
      "crisp",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 12,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "admin-crisp-spacious",
    "family": "admin",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "admin",
      "crisp",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 12,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "admin-hero-compact",
    "family": "admin",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "admin",
      "hero",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 30,
      "borderWidth": 2,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "admin-hero-spacious",
    "family": "admin",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "admin",
      "hero",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 30,
      "borderWidth": 2,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "commerce-glass-compact",
    "family": "commerce",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "commerce",
      "glass",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 24,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "commerce-glass-spacious",
    "family": "commerce",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "commerce",
      "glass",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 24,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "commerce-soft-compact",
    "family": "commerce",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "commerce",
      "soft",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 28,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "commerce-soft-spacious",
    "family": "commerce",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "commerce",
      "soft",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 28,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "commerce-crisp-compact",
    "family": "commerce",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "commerce",
      "crisp",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 12,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "commerce-crisp-spacious",
    "family": "commerce",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "commerce",
      "crisp",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 12,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "commerce-hero-compact",
    "family": "commerce",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "commerce",
      "hero",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 30,
      "borderWidth": 2,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "commerce-hero-spacious",
    "family": "commerce",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "commerce",
      "hero",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 30,
      "borderWidth": 2,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "support-glass-compact",
    "family": "support",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "support",
      "glass",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 24,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "support-glass-spacious",
    "family": "support",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "support",
      "glass",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 24,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "support-soft-compact",
    "family": "support",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "support",
      "soft",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 28,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "support-soft-spacious",
    "family": "support",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "support",
      "soft",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 28,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "support-crisp-compact",
    "family": "support",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "support",
      "crisp",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 12,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "support-crisp-spacious",
    "family": "support",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "support",
      "crisp",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 12,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "support-hero-compact",
    "family": "support",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "support",
      "hero",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 30,
      "borderWidth": 2,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "support-hero-spacious",
    "family": "support",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "support",
      "hero",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 30,
      "borderWidth": 2,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "system-glass-compact",
    "family": "system",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "system",
      "glass",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 24,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "system-glass-spacious",
    "family": "system",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "system",
      "glass",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 24,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "system-soft-compact",
    "family": "system",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "system",
      "soft",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 28,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "system-soft-spacious",
    "family": "system",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "system",
      "soft",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 28,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "system-crisp-compact",
    "family": "system",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "system",
      "crisp",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 12,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "system-crisp-spacious",
    "family": "system",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "system",
      "crisp",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 12,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "system-hero-compact",
    "family": "system",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "system",
      "hero",
      "compact",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 340,
      "height": 112,
      "gap": 8,
      "padding": 14,
      "radius": 30,
      "borderWidth": 2,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  },
  {
    "id": "system-hero-spacious",
    "family": "system",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "system",
      "hero",
      "spacious",
      "native",
      "export-safe"
    ],
    "state": {
      "showHelper": true,
      "showSuccess": false,
      "width": 480,
      "height": 160,
      "gap": 18,
      "padding": 26,
      "radius": 30,
      "borderWidth": 2,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default",
      "label": "Meeting time",
      "description": "Native time field with min, max, step, and accessible helper copy.",
      "helper": "Use 15 minute increments.",
      "errorText": "Choose a time inside office hours.",
      "successText": "Time is available.",
      "value": "09:30",
      "min": "08:00",
      "max": "18:00",
      "step": 900,
      "id": "meeting-time",
      "name": "meetingTime",
      "title": "Meeting time",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "off",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "showSeconds": false,
      "showTimezone": true,
      "timezoneLabel": "Local time",
      "showClearAction": true,
      "required": true,
      "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
      "readOnly": false,
      "invalid": false
    }
  }
];
